@startuml NetExplorerProxy+diagram.completeness
skinparam responseMessageBelowArrow true

title
NetExplorerProxy+test.completeness
end title

participant "Postman\n" as Postman #Orange 
participant "Data\n" as Data
participant "Collection\n" as Collection

'mac-address services
participant "/v1/provide-mac-table-\n     of-all-devices" as macAll #LightBlue
participant "/v1/provide-mac-table-\n     of-specific-device" as macDev #LightBlue
participant "/v1/read-current-mac-\n      table-from-device" as macRead #LightBlue
participant "/v1/receive-current-mac-\n    table-of-device" as macRx #LightBlue
'deviceLists
participant "/v1/provide-list-of-\n     connected-devices" as devList #LightBlue
participant "/v1/provide-list-of-\n     devices-in-nep" as nepList #LightBlue
'device + equip info
participant "/v1/provide-general-\n     information-of-devices" as devInfo #LightBlue
participant "/v1/provide-actual-\n     equipment-of-devices" as equip #LightBlue
'air-interface
participant "/v1/provide-air-interface-\n     general-information-\n    of-devices" as air #LightBlue
participant "/v1/provide-air-interface-\n     transmission-mode-lists-\n     of-devices" as airTml #LightBlue
participant "/v1/provide-air-interface-\n     non-qam-pm-data-\n     of-devices" as airNonQam #LightBlue
participant "/v1/provide-air-interface-\n     qam-pm-data-\n     of-devices" as airQam #LightBlue
'ethernet-container
participant "/v1/provide-ethernet-container-\n     general-information-\n     of-devices" as eth #LightBlue
participant "/v1/provide-ethernet-container-\n     pm-data-\n     of-devices" as ethPm #LightBlue
'wire-interface
participant "/v1/provide-wire-interface-\n     general-information-\n     of-devices" as wire #LightBlue
'statistics
participant "/v1/provide-nep-data-\n     statistics" as stats #LightBlue



group Preparation
  Data --\\o Postman : {servers, mount-name}
  activate Postman
  Postman --\\o Collection : {servers, mount-name}
end

'mac-address services
group /v1/provide-mac-table-of-all-devices
  Collection --\\o Postman: {servers}
  Postman -> macAll: {mount-name}
  macAll <-- Postman: ResponseCode, {ResponseBody}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

group /v1/provide-mac-table-of-specific-device
  Collection --\\o Postman: {servers, mount-name}
  Postman -> macDev: {mount-name}
  Postman <-- macDev: ResponseCode, {ResponseBody: <i>mac-address-data</i>}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

group /v1/read-current-mac-table-from-device
  Collection --\\o Postman: {servers, mount-name}
  Postman -> macRead: {mount-name, <i>dummy-requestor-info</i>}
  Postman <-- macRead: ResponseCode, {ResponseBody: <i>mac-address-data</i>}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

group /v1/receive-current-mac-table-of-device
  Collection --\\o Postman: {servers}
  Postman -> macRx: {request-id, <i>mac-address-data</i>}
  Postman <-- macRx: ResponseCode, {ResponseBody}
  note right Postman #Orange
    check for ResponseCode == 204
  end note
end

'---- deviceList  --------------------------------------------------------------------------------
group /v1/provide-list-of-connected-devices
  Collection --\\o Postman: {servers}
  Postman -> devList
  Postman <-- devList: ResponseCode, {ResponseBody: <i>mount-name-list</i>}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

group /v1/provide-list-of-devices-in-nep
  Collection --\\o Postman: {servers}
  Postman -> nepList
  Postman <-- nepList: ResponseCode, {ResponseBody: <i>mount-name-list</i>}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

'---- deviceInfo + equipmentInfo ----------------------------------------------------------------
group /v1/provide-general-information-of-devices
  Collection --\\o Postman: {servers}
  Postman -> devInfo: {mount-name-list, data-age} (both optional)
  Postman <-- devInfo: ResponseCode, {ResponseBody: <i>csv</i>}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

group /v1/provide-actual-equipment-of-devices
  Collection --\\o Postman: {servers}
  Postman -> equip: {mount-name-list, data-age} (both optional)
  Postman <-- equip: ResponseCode, {ResponseBody: <i>csv</i>}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

'---- air-interface ----------------------------------------------------------------------------
group /v1/provide-air-interface-general-information-of-devices
  Collection --\\o Postman: {servers}
  Postman -> air: {mount-name-list, data-age} (both optional)
  Postman <-- air: ResponseCode, {ResponseBody: <i>csv</i>}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

group /v1/provide-air-interface-transmission-mode-lists-of-devices
  Collection --\\o Postman: {servers}
  Postman -> airTml: {mount-name-list, data-age} (both optional)
  Postman <-- airTml: ResponseCode, {ResponseBody: <i>csv</i>}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

group /v1/provide-air-interface-non-qam-pm-data-of-devices
  Collection --\\o Postman: {servers}
  Postman -> airNonQam: {mount-name-list, data-age} (both optional)
  Postman <-- airNonQam: ResponseCode, {ResponseBody: <i>csv</i>}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

group /v1/provide-air-interface-qam-pm-data-of-devices
  Collection --\\o Postman: {servers}
  Postman -> airQam: {mount-name-list, data-age} (both optional)
  Postman <-- airQam: ResponseCode, {ResponseBody: <i>csv</i>}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

'---- ethernet-container ------------------------------------------------------------------------
group /v1/provide-ethernet-container-general-information-of-devices
  Collection --\\o Postman: {servers}
  Postman -> eth: {mount-name-list, data-age} (both optional)
  Postman <-- eth: ResponseCode, {ResponseBody: <i>csv</i>}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

group /v1/provide-ethernet-container-pm-data-of-devices
  Collection --\\o Postman: {servers}
  Postman -> ethPm: {mount-name-list, data-age} (both optional)
  Postman <-- ethPm: ResponseCode, {ResponseBody: <i>csv</i>}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

'---- wire-interface ---------------------------------------------------------------------------
group /v1/provide-wire-interface-general-information-of-devices
  Collection --\\o Postman: {servers}
  Postman -> wire: {mount-name-list, data-age} (both optional)
  Postman <-- wire: ResponseCode, {ResponseBody: <i>csv</i>}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

'---- statistics ------------------------------------------------------------------------
group /v1/provide-nep-data-statistics
  Collection --\\o Postman: {servers}
  Postman -> : {target-date} (optional)
  Postman <-- : ResponseCode, {ResponseBody: <i>data-statistics</i>}
  note right Postman #Orange
    check for ResponseCode == 200
    check for ResponseBody matches reference schema
  end note
end

deactivate Postman

@enduml