@startuml 032_ProvideAirInterfaceNonQamPmData
skinparam responseMessageBelowArrow true

title PromptForProvidingAirInterfaceNonQamPmDataCausesReadingFromNepCache

participant "external \n(Netexplorer)" as external
participant "NEP://v1/provide-air-interface-non-qam-pm-data-of-devices" as nep
participant "ElasticSearch \n(or database)" as db

external -> nep: {optional: mount-name-list, data-age (BasicAuth)}
activate nep

nep -> db: (apiAuthKey)
db --> nep: {optional: mount-name-list, data-age} (no security)

nep --> external: {(filtered) airInterfaceNonQamPmData} (no security)

deactivate nep
@enduml