@startuml 050_ProvideNepDataStatistics
skinparam responseMessageBelowArrow true

title PromptForProvidingNepDataStatisticsCausesReadingFromNepCache

participant "external \n(Netexplorer)" as external
participant "NEP://v1/provide-nep-data-statistics" as nep
participant "MWDI://v1/provide-list-of-connected-devices" as mwdi
participant "NEP://v1/provide-list-of-devices-in-nep" as nepDeviceList
participant "ElasticSearch \n(or database)" as db

external -> nep: {target-date (optional)}(BasicAuth)
activate nep

note over nep
  <u>GetConnectedDevices</u>
  Get list of currently connected devices from MWDI
end note
nep -> mwdi: (apiAuthKey)
mwdi -> nep: {listOfConnectedDevices} (no security)

note over nep
  <u>GetListOfNepDevices</u>
  Get list of all devices currently found in NEP cache.
end note
nep -> nepDeviceList
nepDeviceList -> nep: {listOf(mountName, lastDataUpdateTimestamp)}

note over nep
  <u>GetNepDataStatistics</u>
  Read number of records where timestamp contains either
  day according to the target-date (if provided) or from today (if not provided)
  for the different data classes
end note
nep -> db: {day-to-filter-for}(apiAuthKey)
db --> nep: {filtered recordCounts per data class} (no security)


note over nep
  From GetListOfNepDevices get:
  - numberOfAllDevicesInNepCache
  - numberOfRecentlyUpdatedDevicesInNepCache (i.e. where the timestamp contains the date from today)
end note
nep --> external: {numberOfConnectedDevices, numberOfAllDevicesInNepCache, \nnumberOfRecentlyUpdatedDevicesInNepCache, \nrecordCountsPerDataClass} (no security)

deactivate nep
@enduml