@startuml 00x_CyclicOperationBasedDeviceListAndDataSync
skinparam responseMessageBelowArrow true

title
PromptForEmbeddingCausesCyclicLoadingOfDeviceListFromMwdi
PromptForEmbeddingCausesCyclicUpdateOfNepDeviceList
PromptForEmbeddingCausesCyclicDeviceDataRetrievalFromMwdi
PromptForEmbeddingCausesCyclicDeletingUnconnectedDevicesFromNepCacheAfterRetentionExpiration
end title

participant "RO" as ro
participant "NEP://v1/embed-yourself" as nep
participant "MWDI://v1/provide-list-of-connected-devices" as mwdiDev
participant "MWDI://core-model-1-4:network-control-domain=cache/\ncontrol-construct={mountName}?fields={nep-1-1-0-string-p-000}" as mwdiCC
participant "ElasticSearch" as es

ro -> nep
activate nep

'general info
note over nep
<b>Cyclic operation starts</b>
- update the internal list of devices and 
- update the cached data for devices
  (retrieval from MWDI, storage in NEP cache) 
end note

'get deviceList from MWDI, update NEP deviceList
note over nep
<b>Update NEP deviceList</b>
- MWDI deviceList sync interval according to 
  <i>deviceListSyncPeriod</i>
- Compare deviceLists from MWDI and NEP:
   - <b><i>add</i></b> new devices from MWDI deviceList
   - <b><i>delete</i></b> devices from NEP deviceList, 
     not found in MWDI deviceList
     if their retention has expired (<i>deviceRetention</i>)
end note
  nep -> mwdiDev
  mwdiDev --> nep: {list of-(mount-name)}
  nep -> es: <i>add/delete mount-names to/from deviceList</i>

'fetch new data
note over nep
  <b>Update NEP cache with new device data</b>
  repeat for each device in deviceList,
  in case of failure, retry according to retry config,
  consider retrieval treshold times for prioritization;
  before writing to NEP cache apply further filtering
end note
  nep -> mwdiCC: {mount-name}
  mwdiCC --> nep: {filtered ControlConstruct}
  nep -> es: {filtered* ControlConstruct}

'delete expired devices and data
note over nep
  <b>Delete old data</b>
  - for each device deleted from NEP deviceList,
    also delete stored data from cache
  - for each device in NEP, delete expired device data
    (data older than <i>dataRetention</i> days)
end note
  nep -> es: <i>delete expired data</i>

deactivate nep

@enduml