@startuml 026_ProvideActualEquipmentDeviceInfo
skinparam responseMessageBelowArrow true

title PromptForProvidingGeneralEquipmentDeviceInfoCausesReadingFromNepCache

participant "external \n(Netexplorer)" as external
participant "NEP://v1/provide-actual-equipment-information-of-devices" as nep
participant "ElasticSearch \n(or database)" as db

external -> nep: {optional: mount-name-list (BasicAuth)}
activate nep

nep -> db: (apiAuthKey)
db --> nep: {optional: mount-name-list} (no security)

nep --> external: {(filtered) actualEquipmentInfo} (no security)

deactivate nep
@enduml