@startuml 041_ProvideEthernetContainerPmData
skinparam responseMessageBelowArrow true

title PromptForProvidingAirInterfacePmDataCausesReadingFromNepCache

participant "external \n(Netexplorer)" as external
participant "NEP://v1/provide-air-interface-general-information-of-devices" as nep
participant "ElasticSearch \n(or database)" as db

external -> nep: {optional: mount-name-list, data-age (BasicAuth)}
activate nep

nep -> db: (apiAuthKey)
db --> nep: {optional: mount-name-list, data-age} (no security)

nep --> external: {(filtered) ethernetContainerPmData} (no security)

deactivate nep
@enduml