@startuml 100_ProvideMacTablesOfAllDevices
skinparam responseMessageBelowArrow true

title PromptForProvidingAllMacTablesCausesReadingMacTablesFromMatrCache

participant "external \n(Netexplorer)" as external
participant "NEP://v1/provide-mac-table-of-all-devices" as nep
participant "MATR://v1/provide-mac-table-of-all-devices" as matr

external -> nep: (BasicAuth)

nep -> matr: (apiAuthKey)
matr --> nep: {list-of(mountName, macAddressCur, egressLtpUUid, originalLtpName, vlanId, macAddresses, timeStampOfRpc)}

nep --> external: {list-of(mountName, macAddressCur, egressLtpUUid, originalLtpName, vlanId, macAddresses, timeStampOfRpc)}


@enduml