@startuml 101_ProvideMacTableOfSpecificDevice
skinparam responseMessageBelowArrow true

title PromptForProvidingMacTableOfSpecificDeviceCausesReadingMacTableFromMatrCache

participant "external \n(Netexplorer)" as external
participant "NEP://v1/provide-mac-table-of-specific-device" as nep
participant "MATR://v1/provide-mac-table-of-specific-device" as matr

external -> nep: {mountName}(BasicAuth)

nep -> matr: {mountName} (apiAuthKey)
matr --> nep: {list-of(mountName, macAddressCur, egressLtpUUid, originalLtpName, vlanId, macAddresses, timeStampOfRpc)}

nep --> external: {list-of(mountName, macAddressCur, egressLtpUUid, originalLtpName, vlanId, macAddresses, timeStampOfRpc)}


@enduml