@startuml 102_ProvideListOfConnectedDevices
skinparam responseMessageBelowArrow true

title PromptForProvidingListOfConnectedDeviceCausesReadingMwdiDeviceList

participant external
participant "NEP://v1/provide-list-of-connected-devices" as nep
participant "MWDI://v1/provide-list-of-connected-devices" as mwdi

external -> nep: (apiKeyAuth)

nep -> mwdi:
mwdi --> nep: {list-of(MountName)}

nep --> external: {list-of(MountName)}

@enduml